### ISSUE TITLE
cannot source function in R

### ISSUE THREAD

**Issue by sailseem** [digitalcytometry/ecotyper#13]
Dear developer,
   Well, i am trying to analyze bulk seq data in the website, after I uploaded the files, it always returned like this
![image](https://user-images.githubusercontent.com/72428172/153734027-8dc37f2a-8dc4-4d8e-8a0f-89b5c11592e2.png)

When I trying to use this in R, I cannot even source("EcoTyper_discovery_bulk.R"). My Rstudio died every time like this
![image](https://user-images.githubusercontent.com/72428172/153734042-b5a3cca5-7aa9-43bb-aa32-6f9b9586a78c.png)

can you help me with this

**Comment by BALuca** [comment]
Hi,

I think you are encountering two separate issues. First, the website seems to be crashing with your data. I was wondering if you could send us the data to ecotyper.stanford@gmail.com, so that we can debug the problem. Second, the EcoTyper source code, although implemented in R, is designed to be run as a command line application, rather than being sourced. If you want to run it form RStudio, instead of running _source("EcoTyper_discovery_bulk.R")_ in the _Console_ tab, you would need to run it from the _Terminal_ tab, using a command line similar to: Rscript EcoTyper_discovery_bulk.R -c config_discovery_bulk.yml. For more information on which EcoTyper command to run, and what command line arguments you need to provide, please check out our Tutorials on github: https://github.com/digitalcytometry/ecotyper#readme

Best,
The EcoTyper team

**Comment by sailseem** [comment]
Thank you very much for your prompt and kind reply. I just sent my file via email for the questions.

Well, regarding question2, I still have some silly questions. Cause I am quite new to this, I find it's kind of difficult in installing packages in Terminal. Could you please tell me what's the command to install the right NMF package in terminal???   Sorry for these troubles, I know it's so silly.

**Comment by BALuca** [comment]
Thank you very much for the data. We sent you a reply regarding the website issue on email.

Regarding question 2, you don't need to install the packages in Terminal again. Once you installed all the required packages once in the console, they will be available when calling the script from the Terminal.

Best,
The EcoTyper team
