### ISSUE TITLE
Highly variable genes / pre-filtering input to EcoTyper_discovery_scRNA.R ?

### ISSUE THREAD

**Issue by semenko** [digitalcytometry/ecotyper#15]
I'm using EcoTyper discovery with scRNA data (Tutorial 5) --

The data I have are pre-filtered per standard workflows (based on counts / fraction of mitochondrial reads, etc.).

I have an enormous selection of **all** genes, as well as a subset of 1,000 highly variable genes (i.e. the output of ```Seurat::FindVariableFeatures``` or ```scanpy.pp.highly_variable_genes```).

**Does EcoTyper expect all genes, or can it process just a subset of highly variable genes?**

**Comment by BALuca** [comment]
Hi, 

We have not explored with using subsets of highly variable genes. That said, my sense is that it is better to use all genes, if possible. This is because, by default, EcoTyper performs an internal feature selection for each cell type. It selects the cell-type specific genes only. This should step help with to the identification of meaningful cell type specific states, rather than generic ones, e.g. metabolic, cell cycle related, etc. If the size of the expression matrix is of concern, I would downsample the cells rather than the genes, as EcoTyper subsets each cell type to 2,500 cells when performing cell state identification anyway.

Best,
The EcoTyper team
