### ISSUE TITLE
Question about rank value selection

### ISSUE THREAD

**Issue by hahahah-single** [digitalcytometry/ecotyper#17]
I try to repeat Tutorial 5,with the data you gave,but I found that the final rank value selection (rank_plot.png)is not the same as the one given in your tutorial. Is the result the same with different versions of R? I want to ask if this is normal and how to choose it？

**Comment by BALuca** [comment]
Hey, can you please send the rank plot you are getting and the configuration file you used, so that we can have a look? You can either post it here or send it to ecotyper.stanford@gmail.com. Also, what R version did you use?

Best,
The EcoTyper team

**Comment by BALuca** [comment]
Hi,

We investigated the issue and it seems that different versions of R can give slightly different results for the example data. This is because some EcoTyper steps, including NMF algorithm initialization, depend on random number generation. Although EcoTyper sets random seeds before each such step, different R version can output different random numbers for the same seed. However, running EcoTyper on the same R version should always give the same results. To mitigate this issue, we recommend at least 50 NMF restarts when running EcoTyper. We also updated the documentation to reflect this behavior.

This is the rank plot I obtained in R 4.0.2:
![rank_plot](https://user-images.githubusercontent.com/36973687/164114262-ccb005fa-21c4-40f5-82e3-c27362aa2b47.png)

Best,
The EcoTyper team
