### ISSUE TITLE
Annotating input cell types; should I be specific or broad?

### ISSUE THREAD

**Issue by semenko** [digitalcytometry/ecotyper#18]
I'm working on a carcinoma dataset, applying EcoTyper in Discovery mode to scRNA data, then Recovery Mode on bulk data.

For input cell types, I'm passing the annotations required by EcoTyper for Carcinoma (e.g. B.cells, Fibroblasts, etc.).

**Should I only annotate cells where I have 100% confidence, or should I be broad in my annotations?**

For example, in a "**Fibroblast**" population, I have a subset that's likely **myofibroblasts** -- should I include those with "Fibroblasts"?

**Comment by BALuca** [comment]
Hi,

Since you are doing discovery in scRNA-seq data, you can annotate the cell types in any way that makes sense for the biological system that you are analyzing, i.e. not necessarily bound to the cell type definitions from the Carcinoma EcoTyper and at different degrees of granularity. Our general loose recommendation is to be as broad as possible. This is because EcoTyper selects for "cell type specific" genes, by performing differential expression between each cell type and the rest of cells. If two very similar cell types are annotated as different categories, some "cell type specific" genes might be left out for not being DE. For your example, I would lean towards including myofibroblasts into the fibroblast category and let EcoTyper resolve this heterogeneity. For carcinoma, EcoTyper was able to identify a myofibroblast-like state amongst the fibroblast states. Hope this helps!

Best,
The EcoTyper team
