### ISSUE TITLE
Problems with step8 discover scRNA ecotypes

### ISSUE THREAD

**Issue by leolambb** [digitalcytometry/ecotyper#3]
Hi,

First off, thanks for the great tool!

I had used the scRNA example data to try to reproduce the scRNA ecotype discovery project. However, I am confused in the step 8 ecotype discovery part.  Base on the R script, the ncol(all_classes) is a fixed number (6, and the colnames(all_classes) include "ID", "State","Freq" ,"Frac","Max","CellType".), which seems odd to me when using it to calculate p. Could you please help me confirm this? The original code is also attached below. Thanks in advance!

 " jaccard = matrix(NA, nrow(clusters), nrow(clusters))
  for(i in 1:(nrow(clusters)))
  {
    for(j in (i):(nrow(clusters)))
    {
      int <- sum(clusters[i,] & clusters[j,]) # number of samples with states of largest fractions in same samples
      idx <- int / (sum(clusters[i,]) + sum(clusters[j,]) - int) 
      p = 1 - phyper(int, sum(clusters[i,]), ncol(all_classes) - sum(clusters[i,]), sum(clusters[j,]))
      if(is.na(p) | (p > 0.1)){
        #idx = 0
      }
      jaccard[i, j] = jaccard[j, i] = idx
    }
  }"
Best,
Leo Lam

**Comment by BALuca** [comment]
Dear Leo Lam,

Thank you for your input, and apologize for the confusion. The code you are pointing to was present in the script, but not active (i.e. line: #idx=0 below is commented out). That code is supposed to set values in the jaccard matrix to 0 when sample overlap between pairs of cell states is not significant. However, we turned off that filter when performing ecotype discovery starting from scRNA-seq data, out of concerns that the jaccard matrix could be over-filtered, due to low number of samples available in a typical scRNA-seq experiment.

In the latest commit, we fixed the p-value calculation, but decided to keep the filter turned off by default. However, we added an option in the configuration file, so that users can activate it by specifying a p-value cutoff above which the jaccard matrix values are set to 0. Please see the latest version of the code and documentation for more information. 

Best,
The EcoTyper team
