### ISSUE TITLE
question regarding abundance table

### ISSUE THREAD

**Issue by kaizen89** [digitalcytometry/ecotyper#51]
Hi,
I am wandering what does the abundance table exactly refer to, is it abundance of cell states among each cell type or is it among all cells. On my data I am not getting a sum of abundance =1 in either case.
Could you please clarify this point?
Thanks!

**Comment by kaizen89** [comment]
Anyone could please comment on this?

**Comment by kaizen89** [comment]
Sorry to insist but this question is really important.

**Comment by BALuca** [comment]
Hi,

Apologize for the confusion and delay. The abundance table refers to the relative abundance of cell states within each cell type. They do not sum up to 1 because the poor-quality states from each cell type are filtered from the analysis, but their share of abundance is not re-distributed to the remaining states.

Best,
The EcoTyper team
