### ISSUE TITLE
Incongruence in Ecotype_Heatmap.pdf, Ecotype_Assignment.txt, and Ecotype_Abundance.txt sample number

### ISSUE THREAD

**Issue by auroramaurizio** [digitalcytometry/ecotyper#54]
Hello,
I am using your really nice and informative online tool: lymphoma ecotyper.

Please, help me with this concern.

In input I provide a LogRPKM table from 80 samples.
All the 80 samples are listed in the output table "Ecotype_Abundance.txt", where is reported the abundance of each lymphoma ecotype in each sample.
Only 65 samples (out of 80) are listed in the "Ecotype_Assignment.txt" table where is reported the assignment of each sample to the lymphoma ecotype with the highest abundance.
Only 73 samples (out of 80) are listed as "user provided data assigned to lymphoma ecotypes" in the "Ecotype_Heatmap.pdf".

Why not all the samples in input are reported in the summary heatmap "Ecotype_Heatmap.pdf" and table ""Ecotype_Assignment.txt" ? Why are these numbers so different?

Thank you very much in advance!
Best,
Aurora

**Comment by BALuca** [comment]
Hi Aurora,

Thank you for reporting this issue with our website. It was expected that Ecotyper_Assignment.txt can contain less samples than Ecotype_Abundance.txt, since not all samples might be assigned a dominant ecotype. However, it was not expected that the heatmap would have a different number of samples than Ecotyper_Assignment.txt. We fixed the bug that was sometimes creating this situation. Now the results should be consistent.

Best,
The EcoTyper team
