### ISSUE TITLE
Ecotype run error

### ISSUE THREAD

**Issue by Panyitong** [digitalcytometry/ecotyper#60]
Warning message:
Strategy 'multiprocess' is deprecated in future (>= 1.20.0). Instead, explicitly specify either 'multisession' or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'.
Warning message:
More than 2500 cells are available for cell type 'CD8.T.cells'. State recovery might take a long time. We recommend using the option -s to downsample the data...
Warning message:
The following cell types are missing from the recovery cohort: B.cells, CD4.T.cells, Dendritic.cells, Endothelial.cells, Epithelial.cells, Fibroblasts, Mast.cells, Monocytes.and.Macrophages, NK.cells, PCs, PMNs. Running ecotype recovery on the remaining ones!
Error in `[<-.data.frame`(`*tmp*`, , col, value = 1L) :
  replacement has 1 row, data has 0
Calls: heatmap_simple -> heatmap_color_annotation -> [<- -> [<-.data.frame
Execution halted
Error in RunJobQueue() :
  EcoTyper failed. Please check the error message above!
Execution halted
~
First of all, I carried out ecotyper on CD8T cells of sample 1 and sample 2 respectively, and sample 1 was able to parse out the three subtypes of CD8T normally, but the above problems appeared in sample 2. I guess it was due to the cells of the sample1. Therefore, I combined sample 1 and sample 2, but the above problems still appeared. I can't figure it out right now. Does anyone know why?

**Comment by BALuca** [comment]
Hi, 

I suspect that the error might be arising due to input annotation file formatting. I would make sure that the file is formatted as described in Tutorial 2; especially that it is tab-separated and that the sample IDs match the sample IDs in the expression matrix. If you are confident that the formatting is correct, would it be possible to send us a reproducible example of the expression and annotation files at ecotyper.stanford@gmail.com, so that we can take a look?

Best,
The EcoTyper team
