### ISSUE TITLE
the percentage of  Single cells assinged to cell state is inaccurate?

### ISSUE THREAD

**Issue by linka0725** [digitalcytometry/ecotyper#7]
Hello, Thank you for sharing such a great job. This is very helpful to my research. 
But I have a problem in the process of using EcoTyper, that is, in the result of output heatmap, the percentage of "Single cells assinged to cell state" is inaccurate. For example, I have a total of 18,828 B cells data as input to EcoTyper, and in the end, only 1,482 cells are assigned to the cell state, but the percentage shows 59%. In theory, it should be only 8%.  This situation will not happen when I input a small number of cells in the dataset, it seems that when the cells number less than 2,000? cells the percentage will be correct, but the dataset with more cells, maybe more than 2,000 or 3,000 cells, the percentage results are basically wrong, so I would like to ask how this error is caused, is it my data problem?
Thank you very much!
![state_assignment_heatmap_00](https://user-images.githubusercontent.com/48084907/146503735-ebfae012-99d9-46c3-9c5a-c590d8b34e43.png)

**Comment by BALuca** [comment]
Hi. Apologize for the confusion! EcoTyper was downsampling by default the single cells to 2500 per cell type, out of consideration for running time, especially when z-score calculation is to be performed - hence the percentage you were obtaining. In the latest commit, we modified this behavior, so that no downsampling is performed by default. If more than 2500 single cells are provided, a warning message about the running time will be printed out, but EcoTyper will run on the complete dataset. In addition, we added an option so that users can specify the cell limit above which downsampling will be performed. Please let us know if you encounter any additional issues after downloading this new version!

Best,
The EcoTyper team

**Comment by linka0725** [comment]
The problem has been solved, thank you very much!
The running time has indeed been much longer (about 3.5 hour for 18828 B cells data), probably because I forgot to set more threads to run. 
By the way,  I have another problem. I noticed that the same cell is sometimes allocated to different states in different data sets, in particular, the same cell in a large dataset and in a small dataset can easily lead to different states, so I wonder if the cell states would be more accurate in the larger dataset.

**Comment by BALuca** [comment]
Hi. EcoTyper scales the expression of each gene to mean 0 and variance 1 across the cells from a given dataset, prior to classification. This and can lead to changing allocation in some rare situations, especially when few cells are available per datasets. However, this effect should be negligible in a large dataset.

**Comment by chengwenxuan1997** [comment]
Sorry, but where could I get the docker image which enables computation on >2500 cells? The ecotyper website will provide a failed download link for the output, thus the online analysis can not be performed.
