### ISSUE TITLE
Using ecotyper on large single-cell data sets

### ISSUE THREAD

**Issue by hahahah-single** [digitalcytometry/ecotyper#8]
Thank you very much for doing such a meaningful work,I am currently using this tool.（1） I have a data set with more than 200,000 cells stored in a sparse matrix format. I would like to ask if you have any suitable processing methods so that it can be run like you did in Tutorial 5, and I want to know if you Have tried a large data set, and evaluated the running time （2）I try to repeat Tutorial 5,with the data you gave,but I found that the final rank value selection (rank_plot.png)is not the same as the one given in your tutorial. I want to ask if this is normal and how to choose it？

**Comment by BALuca** [comment]
Hi. 
Thank you for your interest in EcoTyper. 1) For performance considerations, this version of EcoTyper downsamples each cell type to 2,500 cells when performing discovery on scRNA-seq data (Tutorial 5). Therefore, the running time should be comparable to the run time on the example data in Tutorial 5. To ease the handling of large matrices such yours, you can downsample upfront the sparse matrix so that you have 2,500 cells per cell type, and convert the subset sparse matrix to a conventional matrix. 2) EcoTyper should give the same results for different runs with the same input and same configuration. However, we just realized that an outdated set of results was displayed for Tutorial 5 - apologize for that. We have updated the results. If the rank plot you are getting is still different than the one in Tutorial 5, please let us know at ecotyper.stanford@gmail.com, and we will debug the issue further together.
Best,
The EcoTyper team

**Comment by hahahah-single** [comment]
Thank you very much for your reply, but I now find that the picture still looks different ,I don't know if these problems are caused by differences in operating system version or R language version？At the same time, I would like to ask how the parameter of downsampling 2500 cells is determined and whether it will affect the results if more cells are sampled

**Comment by BALuca** [comment]
Hey, we choose 2,500 cells because, in order to overcome the scRNA-seq dropout and identify robust states, we perform a first round of clustering on the correlation matrix between each pair of cells - that is a 2,500 x 2,500 matrix. The size of this matrix increases quadratically with the number of cells, and that impacts the runtime and the memory necessary to store the matrix. In our test, 2,500 cells gives the best tradeoff between robustness and performance. We are working on solutions to bypass the need of clustering the correlation matrix, but it might take some time until we finalize a new approach.

**Comment by hahahah-single** [comment]
So sorry to reopen this issue,with the same input and same configuration ,I can't get the same picture as rank_plot.png in Tutorial 5,but it's closer ,is this acceptable？ I would like to ask if there is any solution
